[theme]
base="light"

# Widget accent green
primaryColor="#49A65A"

# Main page yellow background
backgroundColor="#D8E09A"

# Sidebar light green panel
secondaryBackgroundColor="#4AA65A"

# Text
textColor="#000000"

font="serif"
